version: "3"

services:

  encrypted-data-project:
    build: .
    ports:
      - 5005:5005
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
#      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
#      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
      - ".:/opt/encrypted-data-project"
      - "/opt/encrypted-data-project/target"
      - "/opt/encrypted-data-project/project/target"
      - "/root/.sbt/1.0/plugins"
