version: "3"

services:

  encrypted-data-project:
    image: encrypted-data-project:latest
    depends_on:
      postgresql-database:
        condition: service_healthy
    environment:
      DATABASE_URL: "jdbc:postgresql://postgresql-database:5432/encrypted-data"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  postgresql-database:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d encrypted-data" ]
      interval: 5s
      timeout: 4s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "encrypted-data"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
