---
- hosts: localhost
  connection: local

  tasks:
    - name: Build production jar files
      shell: cd ../ && sbt universal:packageZipTarball

    - name: Build production Docker image
      shell: docker build -t encrypted-data-project:latest -f ../Dockerfile-prod ../

    - name: Print finish message
      debug:
        msg: Completed building Docker image for encrypted-data-project